# app/resources/data.py

LETTERS_DATA = [
    {
        "l": "A",
        "word": "Apple",
        "scene": "joyfully holding a giant shiny red apple with both hands, smiling at it, apple has a golden glow around it, apple is oversized and cartoonishly perfect",
        "fact": "An apple a day keeps the doctor away, and they taste so juicy and sweet!",
    },
    {
        "l": "B",
        "word": "Butterfly",
        "scene": "laughing with delight as a large magical rainbow-coloured butterfly lands gently on their nose, surrounded by 2–3 more fluttering butterflies nearby",
        "fact": "Butterflies have beautiful wings and flutter around colorful flowers all day!",
    },
    {
        "l": "C",
        "word": "Cat",
        "scene": "sitting cross-legged on the floor, cuddling a fluffy cartoon orange cat in their lap, both looking happy and cozy, soft warm living-room light",
        "fact": "Cats have soft fur and love to purr happily when they get cozy hugs!",
    },
    {
        "l": "D",
        "word": "Duck",
        "scene": "crouching down by a tiny pond puddle, hand outstretched, as a cheerful yellow cartoon duck waddles toward them, water rippling softly",
        "fact": "Ducks go quack quack and love to splash around in fresh water puddles!",
    },
    {
        "l": "E",
        "word": "Elephant",
        "scene": "laughing as a tiny baby cartoon elephant wraps its small trunk around their arm in a playful hug, elephant is soft grey with big floppy ears",
        "fact": "Elephants are the biggest land animals, and they use their long trunks to spray water!",
    },
    {
        "l": "F",
        "word": "Fish",
        "scene": "wide-eyed and excited, holding up a round fishbowl with a single bright orange fish inside, fish and child both making funny surprised faces at each other",
        "fact": "Fish can blow tiny bubbles and swim super fast under the water!",
    },
    {
        "l": "G",
        "word": "Giraffe",
        "scene": "standing next to a tiny cute cartoon giraffe, stretching up on tiptoes trying to reach the giraffe's neck for a hug, both looking adorable",
        "fact": "Giraffes are the tallest animals in the world, stretching up to eat yummy green leaves!",
    },
    {
        "l": "H",
        "word": "Hat",
        "scene": "wearing a comically oversized magical wizard hat covered in stars and moons, hat slightly tilted, arms out for balance, giggling expression",
        "fact": "Hats protect us from the bright sun and look super stylish when we wear them!",
    },
    {
        "l": "I",
        "word": "Ice cream",
        "scene": "holding a towering 3-scoop cartoon ice cream cone with colorful scoops (strawberry, vanilla, chocolate), a tiny bit dripping, eyes wide with joy",
        "fact": "Ice cream is a cool, sweet treat that makes everyone smile on a sunny day!",
    },
    {
        "l": "J",
        "word": "Jar",
        "scene": "peeking curiously into a glowing mason jar full of tiny fireflies, soft golden light illuminating their face with wonder, both hands around the jar",
        "fact": "Jars are perfect for catching glowing fireflies on a magical summer night!",
    },
    {
        "l": "K",
        "word": "Kite",
        "scene": "running joyfully with a large diamond-shaped kite soaring high above, string in both hands, hair and clothes blowing in breeze, blue sky behind",
        "fact": "Kites fly high in the sky, dancing with the wind like colorful birds!",
    },
    {
        "l": "L",
        "word": "Lemon",
        "scene": "making the funniest sour face after biting into a bright cartoon lemon, eyes scrunched, shoulders raised, lemon held dramatically in one hand",
        "fact": "Lemons are bright yellow and have a super sour taste that makes us giggle!",
    },
    {
        "l": "M",
        "word": "Moon",
        "scene": "lying on their back in soft grass, reaching up both arms toward a giant glowing cartoon moon in a starry purple night sky, looking magical and peaceful",
        "fact": "The moon glows brightly in the dark night sky, watching over us while we sleep!",
    },
    {
        "l": "N",
        "word": "Nest",
        "scene": "gently and carefully holding a small cozy bird nest with two tiny eggs inside, kneeling down, expression of gentle wonder and care",
        "fact": "Nests are cozy little homes built by birds to keep their tiny eggs safe and warm!",
    },
    {
        "l": "O",
        "word": "Orange",
        "scene": "peeling a large cartoon orange, spiral peel coming off in one piece, citrus mist in the air, bright and zesty expression, juice slightly spraying",
        "fact": "Oranges are round and juicy, packed with vitamin C to keep us strong and active!",
    },
    {
        "l": "P",
        "word": "Pencil",
        "scene": "seated at a small colourful desk, drawing enthusiastically with a giant oversized magic pencil, sparkling colourful art appearing on the paper in front of them",
        "fact": "Pencils let us draw anything we can imagine, from castles to soaring rockets!",
    },
    {
        "l": "Q",
        "word": "Queen",
        "scene": "proudly wearing a sparkly cartoon crown and a little royal cape, holding a sceptre, standing regally but with a big playful grin, looking adorable not scary",
        "fact": "Queens live in grand castles and wear beautiful sparkly crowns!",
    },
    {
        "l": "R",
        "word": "Rainbow",
        "scene": "arms spread wide in delight, standing under a giant vivid rainbow that arcs across the whole background, soft sunlight and a few white fluffy clouds",
        "fact": "Rainbows are colorful arches in the sky that appear after a fresh rain!",
    },
    {
        "l": "S",
        "word": "Star",
        "scene": "holding a large glowing golden 5-pointed star with both hands above their head, star casting warm sparkly light on their face, night sky full of small stars behind",
        "fact": "Stars twinkle brightly in the night sky like little magical diamonds!",
    },
    {
        "l": "T",
        "word": "Tree",
        "scene": "sitting contentedly in the low wide branch of a friendly cartoon tree, legs dangling, one hand patting the tree trunk, surrounded by green leaves and a butterfly",
        "fact": "Trees have green branches that provide cool shade and cozy homes for birds!",
    },
    {
        "l": "U",
        "word": "Umbrella",
        "scene": "standing under a large colourful polka-dot umbrella, happy and dry while cartoon raindrops fall gently around them, puddles on the ground reflecting colours",
        "fact": "Umbrellas keep us nice and dry when the rain drops fall from the sky!",
    },
    {
        "l": "V",
        "word": "Violin",
        "scene": "standing proudly holding a small cartoon violin under their chin, bow in hand, musical notes floating out in swirling colourful trails, joyful performance face",
        "fact": "Violins make beautiful, sweet music when the bow dances across the strings!",
    },
    {
        "l": "W",
        "word": "Watermelon",
        "scene": "sitting on the ground happily eating a huge cartoon watermelon slice, juice on cheeks, seeds flying out comically, summery joyful expression",
        "fact": "Watermelons are sweet, juicy, and perfect for sharing on hot summer days!",
    },
    {
        "l": "X",
        "word": "Xylophone",
        "scene": "kneeling on the floor banging a bright rainbow-coloured cartoon xylophone with two mallets, musical notes bouncing everywhere, huge smile of musical fun",
        "fact": "Xylophones make happy, chiming sounds when we tap the colorful keys!",
    },
    {
        "l": "Y",
        "word": "Yarn",
        "scene": "sitting surrounded by colourful balls of yarn, playfully tangled in a loop of soft yarn, laughing, with a tiny cartoon kitten also tangled beside them",
        "fact": "Yarn is soft and colorful, and playful little kittens love to roll it around!",
    },
    {
        "l": "Z",
        "word": "Zebra",
        "scene": "laughing and hugging the striped neck of a friendly small cartoon zebra, zebra has big kind eyes and one ear flicked forward curiously, both looking happy",
        "fact": "Zebras have beautiful black and white stripes and run fast across the wild grass!",
    },
]

NUMBERS_DATA = [
    {
        "l": "1",
        "word": "One Sun",
        "scene": "pointing happily at a single bright glowing cartoon sun in a clear blue sky, warm sunlight illuminating their smiling face",
        "fact": "There is only one sun in our sky, and it gives us light and warmth every day!",
    },
    {
        "l": "2",
        "word": "Two Shoes",
        "scene": "sitting on the floor, holding up two brightly colored mismatched cartoon sneakers, looking very proud and ready to walk",
        "fact": "We have two feet, so we need two shoes to run and jump outside!",
    },
    {
        "l": "3",
        "word": "Three Balloons",
        "scene": "holding the strings of three large, round, colorful cartoon balloons (red, blue, and yellow) floating gently above them, joyful expression",
        "fact": "Three colorful balloons can make any day feel like a magical party!",
    },
    {
        "l": "4",
        "word": "Four Wheels",
        "scene": "kneeling beside a shiny red toy car, pointing excitedly at its four black wheels, looking like a little mechanic",
        "fact": "Cars need four round wheels to roll smoothly down the bumpy road!",
    },
    {
        "l": "5",
        "word": "Five Fingers",
        "scene": "holding one hand up high, fingers spread wide open, looking at their hand with a big cheerful smile",
        "fact": "You have five fingers on each hand to help you wave hello to your friends!",
    },
    {
        "l": "6",
        "word": "Six Blocks",
        "scene": "carefully placing the top block on a tall colorful tower made of exactly six building blocks, tongue sticking out slightly in concentration",
        "fact": "Stacking six blocks into a tall tower takes focus, balance, and a steady hand!",
    },
    {
        "l": "7",
        "word": "Seven Colors",
        "scene": "painting a beautiful arc on a large easel, showing all seven colors of a rainbow, holding a big magical paintbrush",
        "fact": "A beautiful rainbow has seven bright colors stretching across the sky!",
    },
    {
        "l": "8",
        "word": "Eight Legs",
        "scene": "looking curiously at a friendly, smiling, fuzzy purple cartoon spider with eight long legs dangling from a web string",
        "fact": "Spiders are amazing little builders that have eight legs to help them spin webs!",
    },
    {
        "l": "9",
        "word": "Nine Stars",
        "scene": "looking up at a magical night sky with exactly nine bright twinkling stars, pointing at them while holding a cozy blanket",
        "fact": "Counting nine bright stars in the night sky is a peaceful way to get ready for bed!",
    },
    {
        "l": "10",
        "word": "Ten Toes",
        "scene": "sitting down barefoot, wiggling their ten little toes playfully, giggling and looking down at their feet",
        "fact": "Wiggling your ten little toes in the soft green grass feels ticklish and fun!",
    },
]
